### ISSUE TITLE
SVG file seems to be ignored

### ISSUE THREAD

**Issue by massimo-cassandro** [brackets-beautify/brackets-beautify#264] opened 2018-06-10 15:22 UTC
Can't beatufy SVG files,

for example, the string

```SVG
<svg height="272" viewBox="0 0 303 272" width="303" xmlns="http://www.w3.org/2000/svg"><path d="m.5.5h302v271h-302z" fill="#d8d8d8" fill-rule="evenodd" stroke="#979797"/></svg>
```
is ignored

Brackets  1.12
Beautify 2.5.2
OSX 10.13.5

**Comment by Hirse** [comment] 2018-08-07 05:12
Duplicate of #223 and #263, see https://github.com/beautify-web/js-beautify/issues/1383 and https://github.com/beautify-web/js-beautify/issues/1027.

**Closed** 2018-08-27 19:26 UTC
Labels: duplicate, js-beautify
