### ISSUE TITLE
static get name get's contatenated

### ISSUE THREAD

**Issue by sielay** [brackets-beautify/brackets-beautify#220] opened 2016-08-25 07:30 UTC
line `static get myField` after `cmd + L` turns into `staticget myField` version 1.2.0

**Comment by Hirse** [comment] 2016-09-04 08:08
What language is this?

Please update to the latest version and try again.

**Comment by sielay** [comment] 2016-09-05 09:59
Will try. That happened in JS in ES6 flavour.

**Comment by Hirse** [comment] 2016-09-05 11:41
Thanks. If you still have issues, could you provide a larger, complete code sample?

**Comment by Hirse** [comment] 2017-03-09 18:59
Closing as I can't reproduce it with version 2.4.0.

**Closed by Hirse** 2017-03-09 18:59 UTC
