### ISSUE TITLE
Problems with filter property in scss.

### ISSUE THREAD

**Issue by GoliafRS** [brackets-beautify/brackets-beautify#214] opened 2016-07-14 16:41 UTC
Before Beautify:
`filter: progid:DXImageTransform.Microsoft.gradient(***);`

After Beautify:
`filter: progid: DXImageTransform.Microsoft.gradient(***);`

Space after progid causes an error at compile scss to css.

**Comment by bitwiseman** [comment] 2016-09-02 20:04
This is fixed in js-beautify 1.6.4.

**Comment by Hirse** [comment] 2016-09-04 07:34
@GoliafRS Please try [v2.3.0](https://github.com/brackets-beautify/brackets-beautify/releases/tag/v2.3.0) which includes an updated js-beautify library.

**Comment by archi-tec** [comment] 2016-10-07 06:42
Hello,
I updated my beautify to 2.3.0, but the problem is still here.

**Comment by Hirse** [comment] 2016-10-07 06:52
@archi-tec Please provide an example for your code and actual and expected output.

**Comment by archi-tec** [comment] 2016-10-07 06:58
@Hirse here is it:

Before
`filter: progid:DXImageTransform.Microsoft.Blur(PixelRadius='3');`

After
`filter: progid: DXImageTransform.Microsoft.Blur(PixelRadius='3');`

**Comment by GoliafRS** [comment] 2016-10-07 09:13
I confirm that the problem is still there.

Before
`filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#000000', endColorstr='#000000', GradientType=1);`

After
`filter: progid: DXImageTransform.Microsoft.gradient(startColorstr='#000000', endColorstr='#000000', GradientType=1);`

**Comment by bitwiseman** [comment] 2016-10-07 22:43
@GoliafRS @archi-tec 
Could you show a but more of the code around these lines? 
Context matters.

**Comment by archi-tec** [comment] 2016-10-08 07:27
@bitwiseman  Here is below. One of these rules is also inside of media query @media(min-width:768px) { ... }, but two others - not.

This is css file, however in scss there is the same issue.
Let me know if you need more.

```
.miami.about-pf16 .blurred-background-container img {
    -webkit-filter: blur(4px);
    -moz-filter: blur(4px);
    -ms-filter: blur(4px);
    -o-filter: blur(4px);
    /* FF doesn't support blur filter, but SVG */
    filter: url("data:image/svg+xml;utf8,<svg height='0' xmlns='http://www.w3.org/2000/svg'><filter id='svgBlur' x='-4%' y='-4%' width='110%' height='110%'><feGaussianBlur in='SourceGraphic' stdDeviation='4'/></filter></svg>#svgBlur");
    filter: progid:DXImageTransform.Microsoft.Blur(PixelRadius='4');
    filter: blur(4px);
}
```

**Comment by bitwiseman** [comment] 2016-10-09 19:28
And the above turns into this? 

```
.miami.about-pf16 .blurred-background-container img {
    -webkit-filter: blur(4px);
    -moz-filter: blur(4px);
    -ms-filter: blur(4px);
    -o-filter: blur(4px);
    /* FF doesn't support blur filter, but SVG */
    filter: url("data:image/svg+xml;utf8,<svg height='0' xmlns='http://www.w3.org/2000/svg'><filter id='svgBlur' x='-4%' y='-4%' width='110%' height='110%'><feGaussianBlur in='SourceGraphic' stdDeviation='4'/></filter></svg>#svgBlur");
    filter: progid: DXImageTransform.Microsoft.Blur(PixelRadius='4');
    filter: blur(4px);
}
```

**Comment by archi-tec** [comment] 2016-10-09 19:34
yes

```
.miami.about-pf16 .blurred-background-container img {
    -webkit-filter: blur(4px);
    -moz-filter: blur(4px);
    -ms-filter: blur(4px);
    -o-filter: blur(4px);
    /* FF doesn't support blur filter, but SVG */
    filter: url("data:image/svg+xml;utf8,<svg height='0' xmlns='http://www.w3.org/2000/svg'><filter id='svgBlur' x='-4%' y='-4%' width='110%' height='110%'><feGaussianBlur in='SourceGraphic' stdDeviation='4'/></filter></svg>#svgBlur");
    filter: progid: DXImageTransform.Microsoft.Blur(PixelRadius='4');
    filter: blur(4px);
}
```

**Comment by bitwiseman** [comment] 2016-10-09 20:20
@archi-tec 
Excellent.  I can reproduces this.  And I found the bug filed for it (that has not been fixed). 
https://github.com/beautify-web/js-beautify/issues/755

**Comment by Hirse** [comment] 2017-03-09 19:02
As the js-beautify issue is closed for js-beautify 1.6.5 I am closing this with version 2.4.0.

**Closed by Hirse** 2017-03-09 19:02 UTC
Labels: js-beautify
