### ISSUE TITLE
Enabling "Beautify on Save" is causing some issues with Live preview

### ISSUE THREAD

**Issue by meetajhu** [brackets-beautify/brackets-beautify#159] opened 2015-05-21 23:46 UTC
Its causing to draw multiple instances of the webpage when i hit save for .html file. Then i have to manually go refresh the chrome browser to display properly again.

**Comment by Hirse** [comment] 2015-11-08 15:33
Duplicate of #49.

**Closed by Hirse** 2015-11-08 15:33 UTC
