### ISSUE TITLE
Beautify on Save goes into infinite loop.

### ISSUE THREAD

**Issue by jfletcher-nuxeo** [brackets-beautify/brackets-beautify#199] opened 2016-02-16 18:01 UTC
2.0.0 on Brackets Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) on OS X 10.11.3.

With `Beatify on Save` enabled when I make a change and save, Brackets goes into some kind of infinite loop. Occasionally I can see the dialog that normally notifies you of external changes but it closes by itself.  I recorded it:

http://g.recordit.co/URSGwleUiN.gif

The problem is the same on Brackets 1.5. The problem does not happen with `brackets-beatify` 1.5.

**Comment by Hirse** [comment] 2016-02-17 20:01
Interesting. I have not seen that myself.
Does this happen reproducably?
Did you see any error messages in the developer tools?

**Comment by jfletcher-nuxeo** [comment] 2016-02-17 21:20
Sorry I forgot to mention, no error messages in the dev tools.  It happens every time, I've had to disable Beautify on Save.  On the other hand I'm kind of liking the manual beautify workflow, hah!

**Comment by sofqi** [comment] 2017-04-24 21:17
I ran into this using tsfmt, if that's of any help (brackets will reload the file, but then thinks it's changed again).

**Comment by seejayjames** [comment] 2018-09-07 00:44
Same issue here. If you delete an ending curly bracket and then save (with Beautify on Save enabled), it goes into the same loop, and tries to keep indenting/formatting the code forever. I thought my computer was possessed at first...but given the thread here, looks like the same issue---it thinks it's changed, or maybe it DID change it, then reloads, re-beautifies, etc....or something.

Note that just clicking Beautify doesn't cause the loop to start. Also note that I do repeated Undos starting at 0:40 to get back to sanity.

It's rather fun to watch, actually...
https://screencast-o-matic.com/watch/cFQiclqpiO

**Comment by Hirse** [comment] 2018-09-07 00:47
@seejayjames Thanks for this frustrating, yet entertaining video. I'll certainly look into it.

I noticed your Brackets showing the "Update available"-icon. Could you give some information on the version you are using?

**Comment by seejayjames** [comment] 2018-09-07 01:30
The version in the video is old, admittedly (1.5). However I just tested with the most current update (1.13.0-17696) and it behaves similarly...not the same visually, but still an endless loop with re-formatting.

Seems like if there's a Beautify action that needs to happen for bad formatting, it saves the file first, then the Beautify change happens, and that sets the file change bit to dirty, then it saves again, Beautify needs to run again, etc......? Just speculating...

**Comment by seejayjames** [comment] 2018-09-07 04:38
Lots more fun with this one, narrowed it down to the curly braces...you can add them while it's looping, and the number of L/R ones determines the direction (auto-indenting is the "culprit"). Note I re-installed Brackets 1.5 to play with it ;)

https://screencast-o-matic.com/watch/cFQifFqprZ

**Comment by Hirse** [comment] 2018-09-07 18:06
Thanks for another great video. 😁 

Since [v2.1.0](https://github.com/brackets-beautify/brackets-beautify/releases/tag/v2.1.0) this extension adds a toolbar button, but I cannot see that in your video. Are you sure you are using this extension and if so, which version?

**Comment by seejayjames** [comment] 2018-09-07 23:08
Ah, it's 2.0.0. I just went back to the most recent Brackets and updated Beautify (2.6.1)....no more weirdness!

That said....I kind of miss it  ;)  buuuuuuut at least it seems to be fine now. Sorry for the noise, I should have updated everything before posting. But it was just so bizarre I thought I'd share, hopefully it was informative...and barring that, entertaining!

**Comment by Hirse** [comment] 2018-09-09 00:15
Great. Thank you for the reports.

I am going to close this issue. Please reopen, if you see any weird behavior.

**Closed by Hirse** 2018-09-09 00:15 UTC
Labels: bug
