### ISSUE TITLE
"Installation failed. The extension encountered an error while starting up."

### ISSUE THREAD

**Issue by SamOxigen** [brackets-beautify/brackets-beautify#254] opened 2017-09-20 21:43 UTC
![image](https://user-images.githubusercontent.com/30326305/30669025-a5361bf2-9e11-11e7-9513-9346e68416fc.png)

This is my brackets' version info:
Release 1.10 build 1.10.0-17483 (release 024bee940)
build timestamp: Wed Jul 05 2017 07:39:31 GMT+0100

my PC: Dell desktop with windows 10 64 bit, intel core i7 processor

I'm getting this message: "Installation failed. The extension encountered an error while starting up."

I'm using the latest brakets, 
I searched for mentioned js files from the attached image (debug output from the installation error) and I couldn't find them in the zip file that I downloaded from the github...

Thanks

**Comment by Hirse** [comment] 2017-09-20 21:49
First of all thank you and apologies for my strictness.

I just tried to install the extension on a fresh Win installation of the latest Brackets and couldn't reproduce your issue, so I have a few follow-up questions:
* Which [installation method](https://github.com/brackets-beautify/brackets-beautify#installation) did you use?
* Which other extensions do you have installed?
* Have you experienced issues with any other extension?
The next might sound stupid, but just to make sure:
* Have you tried restarting Brackets?
* Have you tried re-installing Beautify?

**Comment by SamOxigen** [comment] 2017-09-21 20:01
I install brackets from this site: http://brackets.io/
I have no other extensions installed in my brackets
N/A
dozens times ;)
dozens times ;)

thx

**Comment by Hirse** [comment] 2017-09-21 21:55
Which method did you use to install the extension?

Have you tried to install any other extension and checked if they work?

**Comment by SamOxigen** [comment] 2017-09-22 16:52
1. Extension manager. Also tried to install by directly copying files to extension folder; no success.
2. Yes I did. Some work some don't.

**Comment by Hirse** [comment] 2017-09-24 22:50
That sounds very strange.
Can you see any pattern in the extensions that do work and those that do not?

**Comment by MarQwann-Brown** [comment] 2017-10-19 18:11
I had the same issue but was able to get beautify to install correctly by installing Beautify v2.41 via zip then upgrading to the newest version via the extension manager

**Comment by pmario** [comment] 2017-11-09 22:43
>I had the same issue but was able to get beautify to install correctly by installing Beautify v2.41 via zip then upgrading to the newest version via the extension manager

This worked for me too. ... I did get an installation error with 2.41. ... But it also marked the plugin for update. Clicking the update button seemed to fix the problem.

**Comment by Hirse** [comment] 2017-11-09 22:53
Thanks, @MarQwann-Brown and @pmario.
I'll close this issue then as I don't see anything I can do.

**Closed by Hirse** 2017-11-09 22:53 UTC
Labels: bug
