### ISSUE TITLE
Is it possible not to"beautify" grid-template-areas in css code ?

### ISSUE THREAD

**Issue by ipeanuts07** [brackets-beautify/brackets-beautify#259] opened 2018-02-22 09:30 UTC
Hi there,
Grid system is becoming increasingly common in css layout，many lines of template-areas are organized into one line.
Isn't it possible to set an exception for this ?

**Details about your environment:**
* Brackets Version: latest (release d3b783b99) 
* Brackets Beautify Version: latest 2.5.1

Thanks for answering.

**Comment by Hirse** [comment] 2018-02-22 19:15
This would be something handled by the js-beautify library. Unfortunately, they do not yet have that feature in CSS, but I had opened an issue before: https://github.com/beautify-web/js-beautify/issues/813

(Also, duplicate of https://github.com/brackets-beautify/brackets-beautify/issues/187)

**Comment by bitwiseman** [comment] 2019-03-02 21:37
@ipeanuts07 - css now supports ignoring sections. see https://github.com/beautify-web/js-beautify#ignore-directive

**Closed** 2019-03-04 18:50 UTC
Labels: js-beautify
